version: "3"

volumes:
   spreact_grafana_volume: {}
   spreact_mongo_volume: {}

networks:
   spreact_main_network: {}

services:

   spreact_node_label:
      image: spreact_node_image
      container_name: spreact_node_container
      build:
         context: ./services/node
      ports:
         - ${HOST_NODE_PORT}:${NODE_PORT}
      env_file:
         - .private/node.env
      volumes: 
         - ./app:/app
      networks:
         - spreact_main_network

   spreact_ubuntu_label:
      image: spreact_ubuntu_image
      container_name: spreact_ubuntu_container
      build: ./services/ubuntu
      env_file:
         - .private/ubuntu.env
      # ports:
      #    - 8000:8000
      #    - 5173:5173
      volumes:
         - ./app:/app
      networks:
         - spreact_main_network
      environment:
      #    - GK_PWD=${PWD}
         - NODE_PORT=${NODE_PORT}

   spreact_mongo_label:
      container_name: spreact_mongo_container
      image: spreact_mongo_image
      build:
         context: ./services/mongodb
      env_file:
         - .private/mongo.env
      volumes: 
         - spreact_mongo_volume:/data/db
      networks:
         - spreact_main_network
      # ports:
      #    - 27017:${MONGO_PORT}

   spreact_spring_label:
      image: spreact_spring_image
      container_name: spreact_spring_container
      build:
         context: ./services/spring
      ports:
         - ${HOST_SPRING_PORT}:${SPRING_PORT}
      env_file:
         - .private/spring.env
      volumes: 
         - ./shared/tomcat-logs:/tomcat/logs
         - ./shared/spring-logs:/spring/logs
      networks:
         - spreact_main_network
      depends_on:
         - spreact_mongo_label
