FROM node:latest

# WORKDIR /app
# RUN npm create vite@latest deli_react_app -- --template react-ts

WORKDIR /app/deli_react_app
# RUN npm install

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
